/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kwon37xi' at '16. 1. 1 오후 4:52' with Gradle 2.9
 *
 * @author kwon37xi, @date 16. 1. 1 오후 4:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
